//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenceTracker
    {
        public int Id { get; set; }
        public decimal ExpenceAmount { get; set; }
        public System.DateTime ExpenceDate { get; set; }
        public int ExpenceCategoryId { get; set; }
        public string Description { get; set; }
        public decimal AmountPaid { get; set; }
        public string Status { get; set; }
        public string CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ExpenceCategory ExpenceCategory { get; set; }
    }
}
